project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
    - text: "Proposal"
      href: "Proposal/Proposal.html"
    
    
    - text: "Analysis"
      menu:
        - text: "DataPrepration"
          href: "Actualwork/Dataprep/Dataprep.html"
        - text: "Temperature Analysis"
          href: "Actualwork/Temperature/Temperature.html"
        - text: "Rainfall Analysis"
          href: "Actualwork/Rainfall/Rainfall.html"
        - text: "Wind Analysis"
          href: "Actualwork/Wind/Wind.html"
    
    - text: "R shiny App"
      href: "Rshiny/Rshiny.html"
    
 
    right:
      - href: index.qmd
        text: Home
      - about.qmd


format:
  html:
    theme: 
      - minty
      - theme.scss
    highlight-style: kate
    code-copy: hover
    code-overflow: wrap
    css: styles.css
    toc: true

editor: visual

