project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
    - text: "Proposal"
      href: "Proposal/Proposal.html"
    
    
    - text: "Acutal Work"
      menu:
        - text: "DataPrep"
          href: "Actualwork/Dataprep/Dataprep.html"
    

    
 
    right:
      - href: index.qmd
        text: Home
      - about.qmd


format:
  html:
    theme: 
      - minty
      - theme.scss
    highlight-style: kate
    code-copy: hover
    code-overflow: wrap
    css: styles.css
    toc: true

editor: visual

